language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: aR7V2pw3XEhahJt7nPWUpVU3FhjXPi001G7qBsLDek/AV6RsIzXG1xTy0Oyzz086mTdtq79vDVQ4MBap09Kd1Jz4soMyqo0wKJze1OGEEy+/H5I5DazvHKmGUlXdvgBsZLDvUZbvkBoLWyX/t4kVBG0TxDwOnQgAQ9HwcgKRTXDf4RY6tUAsGtq3RPXRZh3RE17gZpbUym8dWbouZhCWBSm1fssj06JFISisXsG9Oy12JtQXQWAS9xeUFmmCHLdzvA6m8RTDWoHoAKqx3pF+4FhUkfwfeZ7ozq9x/YNpO8rf5uxaNAlIE/pDVFenEERMF69ekHQPNPSYMj3TIftjYg1EhqnXf6HTPn6Biwp6HEpiG2cASumg0l85aL8TqQGqjYH2m8EZofBOiQXF1/SbkezwpdocuEI3RhC7GXXdrSnHB9XGY5A+rPY+NmFx893dksmK6PcQF6xM4jAZC0iUCa67aYSc7Ynyrd7d+ctWHVZlAynQ/SD7ll/ylNckmD2V2gnbL5rQlhAByVZ9A4pAJefWzLlgGbF4YfzbHhPZ9sLEGDZFGWK1sFmBwqbwOz5BUY05d6ROlmTm1j2Kt7edfkNKUUOkxneKc7knR0F2nwb5oQdAXTgkB7P31CiCx+dwzMNCnTGAIA3pzcgDGtmvY6pMiBvit0WZIn/w7uYNg+0=
  app: declutterly-client
  on:
    repo: eliwemyss/declutterly-client
