language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: H6pFSjxHv8XeeHqY3CetxlupeFpMxweAXHMskZa/HFUfv5jr/VGKMHbV/T6dmmZPZmPYscswfB6l+OCPzUDDI7MwU2GCXyRyDG+s6EjrLu6bTKEbec0kB7pI0p/HxipvzZ9j02D6bQWY3rLbgKssQH/laKlXEPv+CwKHWwQw7oe6mkkKsV5hRitckCXY0iiSV+NzcMl+WZ/G9LCJgxEv6iMbcdkZkjQAGDyDQRslNnPwcpKVGJuht3JLexu1kO8+rVUt4RnQGPArlR0jUvNNMqN5ws6BM5Kpoxl+2Xwq+tIU89G/85kbE+3KaCXupcIatIpGsoGLaXkcsdITmJO7Eh0180GXRfmre3EffL+HqrHZ3d3WIyu3/Zo7gJu4JobCsXtEBHlGSvlbSZpXYRkrC82wVVyhIWkgOIcwIm3SyBG8/FS/fBOcQWD4n75YS5AG0wFV7708jCxNezbzXnODbhTihN7Jl4Hqg1NlyMewk0iQWSu2V/rGDWkDCXzcpHlC7nMlLs43gj5lJcXhmpcfDNMxQXdSoFXqK23yk2S4AuDXOAA54LYP7fE41zeaJDeleEQlQgu4WHIPvnOBt6B9hXzartu3pAgTDO43D9V4gNEOul4jRvP5zwMfDXJJ2zElgDsqZLr3W5aE9GKq2R1fp+D8xQzQ7LtTTNYXBnIMVaI=
  app: declutterly-client
  on:
    repo: eliwemyss/declutterly-client
